default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: deakin
  password: deakin
  host: localhost
  port: 3306

development:
  <<: *default
  username: deakin
  password: deakin
  database: sit331-dev

test:
  <<: *default
  database: sit331-test

production:
  <<: *default
  username: deakin
  password: deakin
  database: sit331-prod
